### ISSUE TITLE
Lesson 11 Sidenav does't work with latest MaterializeCSS

### ISSUE THREAD

**Issue by baharalidurrani** [iamshaunjp/materialize-playlist#1]
**Does't work with 1.0.0 stable**
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
**Works with 1.0.0-beta**
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>

**Comment by rongyadong** [comment]
It does work mate. Check your spells may be.

**Comment by baharalidurrani** [comment]
Yes it works!
May be friends @dogfalo fixed it.
Thanks for the response by the way.
